# ===== GENERIC CONSTANTS =====
MAX_CLIENTS = 5

# ===== TCP/IP COMMANDS =====
CMD_CLIENT_SENDBEACON   = 0x01
CMD_CLIENT_REQUESTPOS   = 0x02
CMD_CLIENT_REQUESTTRAJ  = 0x03
CMD_SERVER_SENDPOS      = 0x12
CMD_SERVER_SENDTRAJ     = 0x13
