# ===== GENERIC CONSTANTS =====
MAX_CLIENTS = 5

# ===== TCP/IP SERVER =====
TCPIP_PORT = 31000

# ===== TCP/IP COMMANDS =====
CMD_CLIENT_SENDBEACON   = 0x01
CMD_CLIENT_SENDBEACON_PAYLOAD = 6
CMD_CLIENT_REQUESTPOS   = 0x02
CMD_CLIENT_REQUESTPOS_PAYLOAD = 0
CMD_CLIENT_REQUESTPATH  = 0x03
CMD_CLIENT_REQUESTPATH_PAYLOAD = 0
CMD_SERVER_SENDPOS      = 0x12
CMD_SERVER_SENDPATH     = 0x13
